title: João Firmo
author: João Firmo
email: joaolaiafirmo@gmail.com
description: > # this means to ignore newlines until "exclude"
  Feel free to send me a message, I'm always open for new adventures!

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore

# Date format for posts
# refer to http://shopify.github.io/liquid/filters/date/ if you
# want to customize this
date_format: "%Y"

# generate social links in footer
social_links:
  linkedin: joaofirmo
  behance: joaolaiafirmo
  twitter: joaolaiafirmo
  github: joaofirmo
