title: João Firmo
author: João Firmo
email: joaolaiafirmo@gmail.com
description: >
  Feel free to send me a message, I'm always open for new adventures!

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore

date_format: "%Y"

social_links:
  linkedin: joaofirmo
  behance: joaolaiafirmo
  twitter: joaolaiafirmo
  github: joaofirmo
