title: João Firmo
author: João Firmo
email: joaolaiafirmo@gmail.com
description: > # this means to ignore newlines until "exclude"
  This is the website I made for this course. I really do hope you enjoy it.

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore

# Date format for posts
# refer to http://shopify.github.io/liquid/filters/date/ if you
# want to customize this
date_format: "%b %-d, %Y"

# generate social links in footer
social_links:
  twitter: joaolaiafirmo
  facebook: joaolaiafirmo